name: 'files-have-changed'
description: 'Checks if files have changed since a commit, filtered by globs'
author: 'laurence79'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  since_sha:
    description: 'The commit SHA to compare against'
    required: false
  globs:
    description: 'Globs to filter the changed files. Multi-line string'
    required: false

# Define your outputs here.
outputs:
  has_changes:
    description: 'True if there are changes that match the globs, false otherwise'

runs:
  using: node20
  main: dist/index.js
